networks:
  helpdesk_net:
    driver: bridge

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: helpdesk_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"

    environment:
      - DB_TYPE=postgresdb

      # host.docker.internal permite a Docker acceder a localhost de tu computadora Windows
      - DB_POSTGRESDB_HOST=host.docker.internal
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}

      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}

      # CAMBIAR ESTAS LÍNEAS
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/

      # AGREGAR ESTA LÍNEA
      - N8N_SECURE_COOKIE=false

    volumes:
      - n8n_data:/home/node/.n8n
      - ./data/files:/files

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - helpdesk_net

volumes:
  n8n_data:
